<?xml version="1.0"?>
<package format="3">
  <name>fractal_panda_controllers</name>
  <version>0.1.0</version>
  <description>Commandable impedance controllers used by FRACTAL tactile exploration.</description>
  <maintainer email="adnan.saood@outlook.com">adnan-saood</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <depend>controller_interface</depend>
  <depend>hardware_interface</depend>
  <depend>pluginlib</depend>
  <depend>rclcpp</depend>
  <depend>realtime_tools</depend>
  <depend>trajectory_msgs</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>